- hosts: All
  vars_files:
    - host_vars/Docker.yaml  
  gather_facts: true
  roles:
    - role: common
    - role: volumes
    - role: docker
    - role: start-docker
    - role: couchdb
    - role: docker-swarm