version: "3.2"
services:
  mpi_head:
    image: dispel4py/docker.openmpi
    command: /bin/bash -c "sudo apt-get update && sudo apt-get install -y dnsutils && /usr/sbin/sshd -D"
    networks:
      - mpi-overlay
    volumes:
      - data:/data/share
    ports: 
     - "22"
  
  mpi_node: 
    image: dispel4py/docker.openmpi
    deploy:
      replicas: 3
    volumes:
      - data:/data/share
    networks:
        - mpi-overlay

networks:
  mpi-overlay:
    driver: overlay 
    
volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=172.26.38.63,nolock,soft,rw"
      device: ":/data/share"