# Uninstall old versions of docker
- name: Uninstall old versions of docker
  tags: 'docker'
  become: yes
  apt:
    name: ['docker', 'docker-engine', 'docker.io']
    state: absent


# install dependencies
- name: Install dependencies
  tags: 'docker'
  become: yes
  apt:
    name: ['apt-tansport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
    state: latest
    install_recommends: no


- name: Add apt key of docker
  tags: 'docker'
  become: yes
  apt_key:
    url: https:////download.docker.com/linux/ubuntu/gpg
    state: present

  
- name: Add apt repository and update apt cache
  tags: 'docker'
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower}} {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present

- name: Install docker
  tags: 'docker'
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker-compose
  tags: 'docker'
  become: yes
  pip:
    name: ['docker-compose']
    versions: 1.22.0
    state: present
