
# Create a security group
- name: Create a security group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ security_groups }}'

- name: Create a list of security group names
  set_fact: 
    sg_names: '{{ sg_names|default([]) + [ item.name ]}}'
  loop: '{{ security_groups }}'

- debug:
    msg: "Security group(s) {{ sg_names }} have been created."

#Create security group rules
- name: Create security group rules
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ item.remote_ip_prefix }}'
    state: present
  loop: '{{ security_groups }}'


# Create a internal security group for docker swarm
- name: Create internal security group
  os_security_group:
    name: '{{ security_internal.name }}'
    description: '{{ security_internal.description }}'
    state: present

- debug:
    msg: "Security group(s) {{ security_internal.name }} have been created."


#Create the security group for docker swarm
- name: Create the security group rule for internal security_group
  os_security_group_rule:
    security_group: '{{ security_internal.name }}'
    protocol: '{{ item }}'
    remote_group: '{{ security_internal.remote_group }}'
    state: present
  loop: '{{ security_internal.protocol }}'


- name: get the name of all security group
  set_fact:
    all_sg: "{{ sg_names|union([security_internal.name]) }}"