- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: common
    - role: create-volume
    - role: create-security-group
    - role: create-instance
    - role: write-IP-to-hosts