- name: This is a hello-world example
  hosts: localhost
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      shell: echo "{{item}}"
      with_items:
        - haha
        - heihei
        - hehe
      register: hi_var
    - debug: 
        msg: '{{hi_var.results[0].stdout}}, {{hi_var.results[1].stdout}}, {{hi_var.results[2].stdout}}'
  