- hosts: Docker
  vars_files:
    - host_vars/Docker.yaml
  gather_facts: true
  pre_tasks:
    - name: "Install python"
      raw: sudo apt-get update; sudo apt-get -y install python

  roles:
    - role: common
    - role: volumes
    - role: docker
    - role: start-docker
