- hosts: All
  vars_files:
    - host_vars/Docker.yaml  
  gather_facts: true
  roles:
    - role: common
    - role: volumes
    - role: docker
    - role: start-docker
    - role: docker-swarm

- hosts: Manager
  vars_files:
    - host_vars/Docker.yaml 

  roles:
    - role: couchdb
