# common vars
availability_zone: melbourne-qh2-uom

#Security group
security_groups:
  - name: ssh
    description: "Security group for ssh access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Security group for http access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb
    description: "Open the port for couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

#Security group for docker swarm
security_internal:
  name: internal
  description: "Open the ports used for docker swarm"
  protocol: 
    - tcp
    - udp
    - icmp
  remote_group: internal

instances:
  - name: cloud-1
    group: Manager
    vol_name: vol-cloud-1
    vol_size: 60

  - name: cloud-2
    group: Worker
    vol_name: vol-cloud-2
    vol_size: 60

  - name: cloud-3
    group: Worker
    vol_name: vol-cloud-3
    vol_size: 60

  - name: cloud-4
    group: Worker
    vol_name: vol-cloud-4
    vol_size: 60

instance_image: 37788d15-12bd-488c-b15e-903d43eae051
instance_key_name: MacPro
instance_flavor: uom.mse.2c9g
instance_network: qh2-uom-internal
hosts_path: /etc/ansible/hosts
hosts_file:
  - '[All:children]'
  - Manager
  - Worker
  - ''
  - '[Manager]'
  - ''
  - '[Worker]'
