# common vars
availability_zone: melbourne-qh2-uom



# Volume
volumes:
  - vol_name: vol-cloud-1
    vol_size: 20
  - vol_name: vol-cloud-2
    vol_size: 20
  - vol_name: vol-cloud-3
    vol_size: 20
  - vol_name: vol-cloud-4
    vol_size: 20


#Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for ssh access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for http access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

instances:
  - instance_name: cloud-1
    instance_volumes: vol-clod-1
  - instance_name: cloud-2
    instance_volumes: vol-clod-2
  - instance_name: cloud-3
    instance_volumes: vol-clod-3
  - instance_name: cloud-4
    instance_volumes: vol-clod-4


instance_name: cloud
instance_image: 955a0556-1224-4499-a895-87d54d5cbf32
instance_key_name: MacPro
instance_flavor: uom.general.2c8g
