
- name: get the hosts 
  lineinfile:
    dest: "{{shared_foler}}/hostfile"
    line: "{{ item }}  slots=2"
    insertafter: EOF
    create: yes
    owner: "{{ mpi_user }}"
    group: "{{ mpi_user }}" 
  with_items:
    "{{groups['All']}}"

- name: copy the script to nfs server
  copy:
    src: '{{mpi_script_path}}'
    dest: '{{shared_foler}}'

- name: run the script
  shell: >
     mpirun --mca btl_tcp_if_include eth0 -hostfile {{shared_foler}}/hostfile {{shared_foler}}/{{mpi_script}}
  register: output
  

- debug:
    msg: '{{output.stdout}}'