- name: generate the hosts file
  lineinfile:
    dest: "{{shared_foler}}/hostfile"
    line: "{{ item }}  slots=2"
    insertafter: EOF
    create: yes
    owner: "{{ mpi_user }}"
    group: "{{ mpi_user }}" 
  with_items:
    "{{groups['All']}}"

# - name: run the script
#   shell: >
#      nohup mpirun --mca btl_tcp_if_include eth0 -hostfile {{shared_foler}}/hostfile {{shared_foler}}/{{mpi_script}}
#   register: output
  

# - debug:
#     msg: '{{output.stdout}}'