# Volume
volumes:
  - device: /dev/vdb
    mountpoint: var/lib/docker
    
internet_proxy:
  - http_proxy="http://wwwproxy.unimelb.edu.au:8000"
  - https_proxy="http://wwwproxy.unimelb.edu.au:8000"
  - ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"
  - no_proxy="localhost,127.0.0.1,127.0.1.1,ubuntu"

docker_proxy_remote:
  /etc/systemd/system/docker.service.d/http-proxy.conf

docker_proxy_directory:
  /etc/systemd/system/docker.service.d

couchdb:
  user: admin
  pass: admin
  coockie: unimelb-comp90024-group-61
  secret: mysecret

TEMP_LOCATION: /tmp/openmpi
FINAL_LOCATION: /opt/openmpi-1.10.2
DEBUG_LOCATION: /tmp/openMPI-examples
