
# Install dependencies on the host
- name: Install pip
  become: yes
  apt: 
    name: ['python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update: sudo apt-get install python-pip


- name: Install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest
  #pip install openstacksdk

