
# Uninstall old versions of docker
- name: Uninstall old versions of docker
  tags: 'docker'
  become: yes
  apt:
    name: ['docker', 'docker-engine', 'docker.io']
    state: absent


- name: Install dependencies
  tags: 'docker'
  become: yes
  




- name: Show images
  debug: 
    msg: "Image name:{{ item.name }}; Image id: {{ item.id }}"
  loop: '{{ image_facts }}'